import 'server-only'
import fs from 'node:fs'
import path from 'node:path'
import YAML from 'yaml'

/** Absolute path to the site configuration file (committed to Git). */
const siteConfigPath = path.join(process.cwd(), 'content', 'site.yaml')

/** Allowed values for Giscus boolean-like flags (stored as `0`/`1` in YAML). */
const GISCUS_FLAG_VALUES = ['0', '1'] as const

/** Allowed values for the Giscus comment input position. */
const GISCUS_INPUT_POSITIONS = ['top', 'bottom'] as const

/**
 * Giscus (GitHub Discussions) comment configuration.
 *
 * Mirrors the `giscus` block of `content/site.yaml`. Values are generated by
 * https://giscus.app. Exported so the client-side `Comments` component can type
 * its `config` prop via `import type` (compile-time erasure keeps this
 * server-only module out of the client bundle).
 */
export interface GiscusConfig {
  /** GitHub repository full name (`owner/repo`) with Discussions enabled. */
  repo: string
  /** Repository ID (base64, generated by giscus.app). */
  repoId: string
  /** Discussions category used for post comment threads (e.g. `Comments`). */
  category: string
  /** Category ID (base64, generated by giscus.app). */
  categoryId: string
  /** Path-to-Discussion mapping strategy (e.g. `pathname`). */
  mapping: string
  /** Whether reactions are enabled (`0` off / `1` on). */
  reactionsEnabled: '0' | '1'
  /** Comment box position relative to the thread (`top` or `bottom`). */
  inputPosition: 'top' | 'bottom'
  /** Strict path matching (`0` off / `1` on). */
  strict: '0' | '1'
  /** Whether to emit Discussion metadata to the page (`0` off / `1` on). */
  emitMetadata: '0' | '1'
}

/** Raw shape of `content/site.yaml` - static site identifiers. */
interface SiteConfigRaw {
  /** GitHub login used by the profile card and external links. */
  githubUsername: string
  /** Site title shown in the header, mobile drawer, and browser tab metadata. */
  siteTitle: string
  /** Default site description for SEO metadata and Open Graph. */
  siteDescription: string
  /** Giscus comment configuration (generated by giscus.app). */
  giscus: GiscusConfig
}

/** Resolved site configuration, including derived and environment-sourced fields. */
export interface SiteConfig extends SiteConfigRaw {
  /** Full GitHub profile URL, derived from `githubUsername`. */
  githubUrl: string
  /** Public site URL (from `NEXT_PUBLIC_SITE_URL`), used for SEO metadata and Open Graph. */
  siteUrl: string
}

/**
 * Asserts that a value is a non-empty string, throwing a field-specific error.
 *
 * @param value - The candidate value.
 * @param field - Dotted field name for the error message (e.g. `giscus.repo`).
 * @throws When the value is missing, non-string, or empty.
 */
function assertNonEmptyString(value: unknown, field: string): asserts value is string {
  if (typeof value !== 'string' || value.length === 0) {
    throw new Error(
      `Invalid site config: field "${field}" in ${siteConfigPath} must be a non-empty string`,
    )
  }
}

/**
 * Asserts that a value is one of the allowed literal values.
 *
 * @param value - The candidate value.
 * @param field - Dotted field name for the error message.
 * @param allowed - Permitted literal values.
 * @throws When the value is not among the allowed values.
 */
function assertOneOf<T extends string>(
  value: unknown,
  field: string,
  allowed: readonly T[],
): asserts value is T {
  if (!allowed.includes(value as T)) {
    throw new Error(
      `Invalid site config: field "${field}" in ${siteConfigPath} must be one of ${allowed.join(', ')}`,
    )
  }
}

/**
 * Validates the `giscus` sub-block of the raw site configuration.
 *
 * @param block - The parsed `giscus` value from the raw config.
 * @throws When the block is missing or any field is missing/empty/invalid.
 */
function validateGiscusConfig(block: unknown): asserts block is GiscusConfig {
  if (typeof block !== 'object' || block === null) {
    throw new Error(`Invalid site config: "giscus" block in ${siteConfigPath} is missing`)
  }

  const candidate = block as Record<string, unknown>
  assertNonEmptyString(candidate.repo, 'giscus.repo')
  assertNonEmptyString(candidate.repoId, 'giscus.repoId')
  assertNonEmptyString(candidate.category, 'giscus.category')
  assertNonEmptyString(candidate.categoryId, 'giscus.categoryId')
  assertNonEmptyString(candidate.mapping, 'giscus.mapping')
  assertOneOf(candidate.reactionsEnabled, 'giscus.reactionsEnabled', GISCUS_FLAG_VALUES)
  assertOneOf(candidate.inputPosition, 'giscus.inputPosition', GISCUS_INPUT_POSITIONS)
  assertOneOf(candidate.strict, 'giscus.strict', GISCUS_FLAG_VALUES)
  assertOneOf(candidate.emitMetadata, 'giscus.emitMetadata', GISCUS_FLAG_VALUES)
}

/**
 * Validates that every required field is present and well-formed.
 *
 * @param raw - Parsed raw site configuration.
 * @throws When any required field is missing, non-string, or empty.
 */
function validateSiteConfig(raw: unknown): asserts raw is SiteConfigRaw {
  if (typeof raw !== 'object' || raw === null) {
    throw new Error(`Failed to parse ${siteConfigPath}: expected a YAML mapping at the top level`)
  }

  const candidate = raw as Record<string, unknown>
  const requiredKeys: (keyof SiteConfigRaw)[] = ['githubUsername', 'siteTitle', 'siteDescription']

  for (const key of requiredKeys) {
    assertNonEmptyString(candidate[key], key)
  }

  validateGiscusConfig(candidate.giscus)
}

/**
 * Loads, parses, and validates `content/site.yaml`.
 *
 * @returns Resolved raw site configuration.
 * @throws When the file is missing, unparseable, or fails field validation.
 */
function loadSiteConfigRaw(): SiteConfigRaw {
  let raw: string
  try {
    raw = fs.readFileSync(siteConfigPath, 'utf8')
  } catch {
    throw new Error(`Site config not found: ${siteConfigPath} is missing`)
  }

  const parsed = YAML.parse(raw)
  validateSiteConfig(parsed)
  return parsed
}

/** Cached site configuration (loaded once per process lifetime). */
let cached: SiteConfig | null = null

/**
 * Loads site configuration, caching the result at module scope.
 *
 * @returns Fully resolved site configuration (raw fields + derived/env fields).
 */
function loadSiteConfig(): SiteConfig {
  if (cached) return cached

  const raw = loadSiteConfigRaw()
  cached = {
    ...raw,
    githubUrl: `https://github.com/${raw.githubUsername}`,
    siteUrl: process.env.NEXT_PUBLIC_SITE_URL ?? 'https://ruixe-blog.vercel.app',
  }
  return cached
}

/**
 * Central site-wide configuration.
 *
 * Eagerly loaded and validated at module evaluation time (fail-fast) from
 * `content/site.yaml`. `siteUrl` is sourced from the `NEXT_PUBLIC_SITE_URL`
 * environment variable because preview and production deployments may differ.
 */
export const siteConfig: SiteConfig = loadSiteConfig()
